Allow using jest-prop-type-error with Create React App
esphen/jest-prop-type-error pull request #2
Opened 2018-10-31 17:53 UTC by YPCrumble

Hi - thanks so much for this package! Very useful.

Here's a PR to allow easy integration with Create React App. Let me know what you think or if you have any suggested changes?

2018-10-31 19:02 UTC, eliihen requested changes
Thanks for this PR!

I will absolutely merge something which makes this library easier to use for `create-react-app` users. The documentation is great, but I have a comment on the code change. Have a look at that and we can merge this!

2018-10-31 19:02 UTC, eliihen commented on index.js
> +module.exports = console.error;
This line is actually not needed. The module mutates the global console object, and thus does not need to expose anything.
I double-checked this in create-react-app, and it works fine without any changes.
Take out this line and I will merge the change to the README :slightly_smiling_face:

2018-11-01 14:46 UTC, YPCrumble commented on index.js
> +module.exports = console.error;
@esphen you're absolutely right, thanks for the review!

2018-11-01 14:48 UTC, YPCrumble commented
@esphen just updated my PR :). Thanks!

2018-11-01 15:55 UTC, eliihen approved these changes

2018-11-01 15:56 UTC, merged

2018-11-01 15:56 UTC, esphen commented
Thanks again for the PR!